cs50w-web-development/project2/auctions/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name="auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("new", views.new, name="new"),
    path("auction/<int:auction_id>", views.auction, name="auction"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("addtowatchlist/<int:auction_id>", views.addtowatchlist, name="addtowatchlist"),
    path("removefromwatchlist/<int:auction_id>", views.removefromwatchlist, name="removefromwatchlist"),
    path("categories", views.categories, name="categories"),
    path("categories/<int:category_id>", views.category_auctions, name="category_auctions"),
    path("close/<int:auction_id>", views.close_auction, name="close_auction"),
    path("add_comment/<int:auction_id>", views.add_comment, name="add_comment"),
    path("mybids", views.my_bids, name="my_bids")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cs50w-web-development/project2/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

cs50w-web-development/project2/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    """
    A class to represent a user
    The class inheriths from django super class AbstractUser.
    """
    def __str__(self):
        return f"{self.username}"

class Auction(models.Model):
    """
    Represent every auction on the web application
    The model inherits from django models class
    """
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="seller")
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=1000)
    initial_price = models.IntegerField()
    last_bid_price = models.IntegerField(default=0)
    image = models.ImageField(upload_to="auctions/static/auctions/images/", null=True, blank=True) # CONSIDER REMOVE BLANK AND NULL MAY NOT BE NEEDED
    category = models.ForeignKey("Category", on_delete=models.CASCADE, related_name="cat")
    created_date = models.DateTimeField(auto_now_add=True)
    num_of_bids = models.IntegerField(default=0)
    status = models.BooleanField(default=True)
    winner_user_id = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"AuctionID: {self.id}, Item: {self.title}, InitialPrice: {self.initial_price}, Category: {self.category}"

class Bid(models.Model):
    """
    Represents bids information for each auction
    """
    auction_id = models.ForeignKey("Auction", on_delete=models.CASCADE, related_name="auction_id")
    price = models.IntegerField()
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_id")
    bid_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"BidPrice: {self.price}, Bidder: {self.buyer}, BidDate: {self.bid_date}"

class Comment(models.Model):
    """ Represents comments on auctions """
    auction = models.ForeignKey("Auction", on_delete=models.CASCADE, related_name="auctionID")
    commenter = models.ForeignKey("User", on_delete=models.CASCADE, related_name="commenter")
    comment = models.CharField(max_length=500)

    def __str__(self):
        return f"{self.comment}"


class Category(models.Model):
    """ Represents categories for auctions """
    name = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"

class Watchlist(models.Model):
    """ Represnts users watchlists """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    item = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="item")

    def __str__(self):
        return f"UserID: {self.user.id}, Item: {self.item.title}"

cs50w-web-development/project2/auctions/forms.py
from django import forms
from django.forms import ModelForm
from .models import User, Auction, Bid, Comment, Category, Watchlist


class NewAuction(forms.ModelForm):
    """
    Django form to populate the new auction item
    """
    class Meta:
        model = Auction
        fields = ["title", "description", "initial_price", "image", "category"]
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control", "name": "title"}),
            "description": forms.Textarea(attrs={"class": "form-control", "name": "description"}),
            "initial_price": forms.NumberInput(attrs={"class": "form-control", "name": "initial_price"}),
            "image": forms.ClearableFileInput(attrs={"class": "form-control-file", "name": "image"}),
            "category": forms.Select(attrs={"class": "form-control", "name": "category"}),
        }

cs50w-web-development/project2/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import User, Auction, Bid, Comment, Category, Watchlist
from .forms import NewAuction
from . import util


def login_view(request):
    """
    The login function responsible for logging in users
    """

    # POST request
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })

    # GET request
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    """
    Logging out user from the web application
    """
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    """
    Register new user to the web application
    """

    # POST request
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


def index(request):
    """
    Shows grid of active auctions
    """
    return render(request, "auctions/index.html", {
        "items": Auction.objects.all()
    })


def auction(request, auction_id):
    """
    Auction infromation page
    Users can see all of the detailes about the auction and make their own bid if they want to
    """

    # Extracting data about the auction from the database
    user_id = request.user.id
    listing = Auction.objects.filter(id=auction_id)
    bids = Bid.objects.filter(auction_id=auction_id)
    comments = Comment.objects.filter(auction=auction_id)
    in_watchlist = util.in_watchlist(user_id, listing[0].id)

    # POST request
    if request.method == "POST":
        # Updating latest bid price and num of bids from the bids model
        if len(bids) > 0:
            listing.update(last_bid_price=bids[len(bids)-1].price, num_of_bids=len(bids))

        # Extracting the user new bid if he decided to bid on the item
        bid = request.POST.get("bid_price")

        # Data validation of the input
        try:
            bid = int(bid)
        except ValueError:
            return render(request, "auctions/auction.html", {
                "listing": listing[0],
                "error": "Wrong input number for a bid",
                "user_obj": request.user,
                "comments": comments
            })

        # If the new bid is greater than the last bid and the initial price, add the bid
        if bid > listing[0].initial_price and bid > listing[0].last_bid_price:
            new_bid = Bid()
            new_bid.auction_id = listing[0]
            new_bid.price = bid
            new_bid.buyer = request.user
            new_bid.save()
            bids = Bid.objects.filter(auction_id=auction_id)
            listing.update(last_bid_price=bid, num_of_bids=len(bids))
            # Render the auction page with success message
            return render(request, "auctions/auction.html", {
                "listing": listing[0],
                "message": "You placed your bid successfully",
                "user_obj": request.user,
                "comments": comments
            })

        # User tried to bid a price that is lower than the last bid, render the auction page with error message
        else:
            return render(request, "auctions/auction.html", {
                "listing": listing[0],
                "error": "Bid price should be greater than initial price and the last bid price",
                "user_obj": request.user,
                "comments": comments
            })

    # GET request
    # Render the auction page with the relevant data
    else:
        if len(bids) > 0:
            # Checking if the user that visit this auction won the item, and if he does render a winner message
            if listing[0].status == False and request.user.id == listing[0].winner_user_id:
                return render(request, "auctions/auction.html", {
                    "listing": listing[0],
                    "in_watchlist": in_watchlist,
                    "user_obj": request.user,
                    "comments": comments,
                    "winner": f"You won this auction for ${listing[0].last_bid_price}"
                })

            # Render the page with relevant data
            listing.update(last_bid_price=bids[len(bids)-1].price, num_of_bids=len(bids))
            return render(request, "auctions/auction.html", {
                "listing": listing[0],
                "in_watchlist": in_watchlist,
                "user_obj": request.user,
                "comments": comments,
            })

        # Render the page with relevant data
        else:
            return render(request, "auctions/auction.html", {
                "listing": listing[0],
                "in_watchlist": in_watchlist,
                "user_obj": request.user,
                "comments": comments,
            })


@login_required(login_url='/login')
def new(request):
    """
    Create new auction listing
    Users specify a title for the listing, a text-based description, and what the starting bid price should be.
    Also users load an image for the listing and select the category of the item
    """

    # POST request
    if request.method == "POST":
        # Creating new auction model object
        it = Auction()

        # Creating new form for the item
        item = NewAuction(request.POST, request.FILES)

        # Check if the form fields inputs are valid
        if item.is_valid():
            # Saving the input inserted into the form to the new auction model object
            it.seller = request.user
            it.title = item.cleaned_data["title"]
            it.description = item.cleaned_data["description"]
            it.initial_price = item.cleaned_data["initial_price"]
            it.image = item.cleaned_data["image"]
            it.category = item.cleaned_data["category"]
            it.save()

        # Rendering the index page with the new auction included and an success message
        return render(request, "auctions/index.html", {
            "message": "Item added successfuly",
            "items": Auction.objects.all()
        })

    # GET request
    # Render the form so the user could add its item
    return render(request, "auctions/new.html", {
        "form": NewAuction
    })


@login_required(login_url='/login')
def watchlist(request):
    """
    Users who are signed in should be able to visit a Watchlist page,
    which should display all of the listings that a user has added to their watchlist.
    Clicking on any of those listings should take the user to the listing page.
    """

    # Extracting data about the auction and the user that initate the request
    user_id = request.user.id
    auctions = Watchlist.objects.filter(user=user_id)

    # Rendering the watch list
    return render(request, "auctions/watchlist.html", {
        "auctions": auctions,
        "num_of_auctions": len(auctions)
    })


@login_required(login_url="/login")
def addtowatchlist(request, auction_id):
    """
    Adding item to the user watchlist
    """

    # Extracting data about the auction and the user that initate the request
    user_id = request.user.id
    auction = Auction.objects.get(id=auction_id)

    # If the user tries to add his own item to the watchlist through URL manipulation
    # Render the item page and don't add the item to the user watchlist
    if auction.seller == request.user:
        return HttpResponseRedirect(reverse("auctions:auction", args=[auction_id]))

    # Checking if the item is already in the watchlist of the user
    # I am doing so to prevent users add duplications thorugh URL manipulation
    already = util.in_watchlist(user_id, auction_id)
    # If the item is not in the user watchlist add it to the watchlist and render thw watchlist
    if not already:
        new_item = Watchlist()
        new_item.user = request.user
        new_item.item = Auction.objects.get(id=auction_id)
        new_item.save()
        return HttpResponseRedirect(reverse("auctions:watchlist"))
    # If the item is already in the user watchlist render the auction page and don't add the item again to the user watchlist
    else:
        return HttpResponseRedirect(reverse("auctions:auction", args=[auction_id]))


@login_required(login_url="/login")
def removefromwatchlist(request, auction_id):
    """
    Remove item from user watchlist
    """
    Watchlist.objects.filter(user=request.user.id, item=auction_id).delete()
    return HttpResponseRedirect(reverse("auctions:watchlist"))


def categories(request):
    """

cs50w-web-development/project2/auctions/templates/auctions/auction.html
{% extends "auctions/layout.html" %}
{% load static %}
{% load my_filters %}
{% block body %}
    {% if message %}
    <div class="alert alert-success" role="alert">
        {{ message }}
    </div>
    {% endif %}

    {% if error %}
    <div class="alert alert-danger" role="alert">
        {{ error }}
    </div>
    {% endif %}

    {% if winner %}
        <div class="alert alert-success" role="alert">
            {{ winner }}
        </div>
    {% endif %}
    <br>
    <div class="text-center auction-details">
        <h2>{{ listing.title }}</h2>
        <br>
        <img style="width: 100%; max-width: 25rem;" src="{{listing.image.url}}" class="img-fluid rounded">
        <br>
        <p style="font-size:24px; max-width:800px">{{ listing.description }}</p>
        <br>
        {% if listing.status %}
            <p class="badge-text badge badge-success">Active</p>
        {% else %}
            <p class="badge-text badge badge-danger">Closed</p>
        {% endif %}
        <br>
        <div class="text-left">
            <p>Category:&nbsp&nbsp{{ listing.category }}</p>
            <p>Initial price:&nbsp&nbsp{{ listing.initial_price|currency }}</p>
            <p>Number of bids:&nbsp&nbsp{{ listing.num_of_bids }}</p>
            <p>Last bid price:&nbsp&nbsp{{ listing.last_bid_price|currency }}</p>
        </div>
        <br>
        {% if listing.seller != user_obj %}
            {% if user.is_authenticated and listing.status %}
                <form action="{% url 'auctions:auction' auction_id=listing.id %}" method="post" id="bid_form">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="input-group bid-spacing">
                            <div class="d-flex">
                                <div class="input-group-prepend"><span class="input-group-text">$</span></div>
                                <input type="text" class="form-control" name="bid_price" id="bid_price" aria-label="Amount (to the nearest dollar)">
                            </div>
                            <button type="submit" form="bid_form" class="btn btn-dark">Place Bid</button>
                        </div>
                    </div>
                    <br>
                </form>
                {% if in_watchlist %}
                    <a href="{% url 'auctions:removefromwatchlist' auction_id=listing.id %}" class="btn btn-dark">Remove from Watchlist</a>
                {% else %}
                    <a href="{% url 'auctions:addtowatchlist' auction_id=listing.id %}" class="btn btn-dark">Add to Watchlist</a>
                {% endif %}
            {% endif %}
        {% else %}
            <form action="{% url 'auctions:close_auction' auction_id=listing.id%}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-dark">Close Auction</button>
            </form>
        {% endif %}
    </div>


    <hr class="hr-style">
    <br>
    <div class="row d-flex justify-content-center">
        <div class="col-md-8 col-lg-6">
          <div class="card shadow-0 border" style="background-color: #f0f2f5;">
            <div class="card-body p-4">
              <div class="form-outline mb-4">
                {% if user.is_authenticated %}
                <form action="{% url 'auctions:add_comment' auction_id=listing.id %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="comment" id="comment" class="form-control" placeholder="Type comment..." />
                    <br>
                    <button type="submit" class="btn btn-dark">Send</button>
                </form>
                {% else %}
                    <a href="/login" class="btn btn-dark">Login to add comments</a>
                {% endif %}
              </div>
              {% for cm in comments %}
                <div class="card">
                    <div class="card-body">
                    <p>{{cm.comment}}</p>
                    <div class="d-flex justify-content-between">
                        <div class="d-flex flex-row align-items-center">
                        <p class="small mb-0 ms-2">{{cm.commenter.username}}</p>
                        </div>
                    </div>
                    </div>
                </div>
                <br>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
{% endblock %}

cs50w-web-development/project2/auctions/templates/auctions/auction_summary.html
{% extends "auctions/layout.html" %}
{% load static %}
{% load my_filters %}
{% block body %}
    {% if message %}
        <div class="alert alert-success" role="alert">{{ message }}</div>
    {% endif %}
    <br>
    <h2>Auction Summary</h2>
    <br>
    <div class="align-center-col">
        <p>The price you sold your item: {{winner_bid.price|currency}}</p>
        <p>User who bought your item: {{winner_bid.buyer.username}}</p>
    </div>
{% endblock %}

cs50w-web-development/project2/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}
{% load static %}
{% load my_filters %}
{% block body %}
    <br>
    <h2>Categories</h2>
    <br>
    <div class="list-group align-center">
        {% for cat in categories %}
            <a class="w-50 align-center" href="{% url 'auctions:category_auctions' category_id=cat.id %}"><button type="button" class="list-group-item list-group-item" style="width:100%;">{{ cat }}</button></a>
            <br>
        {% endfor %}
    </div>
{% endblock %}

cs50w-web-development/project2/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}
{% load my_filters %}
{% block body %}
    {% if message %}
        <div class="alert alert-success" role="alert">{{ message }}</div>
    {% endif %}
    <br>
    <h2>Active Auctions</h2>
    <br>
        {% for item in items %}
            {% if item.status %}
            <div class="align-center">
                <div class="card text-center mb-5" style="width: 50rem;">
                    <div class="card-header">{{item.category}}</div>
                    <div class="align-center">
                        <img src="{{item.image.url}}" class="card-img-top" alt="{{item.title}} image" style="width: 100%; max-width: 25rem;"/>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ item.title }}</h5>
                        {% if item.num_of_bids > 0 %}
                            <p class="card-text card-price">{{ item.last_bid_price|currency }}</strong></p>
                        {% else %}
                            <p class="card-text card-price">{{ item.initial_price|currency }}</strong></p>
                        {% endif %}
                        <a href="{% url 'auctions:auction' auction_id=item.id %}" class="btn btn-dark">Auction Page</a>
                    </div>
                    <div class="card-footer text-muted">{{item.created_date}}</div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

cs50w-web-development/project2/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Popit{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <link rel="icon" href="{% static 'auctions/assets/POPIT-icon.png' %}" type="image/x-icon">
    </head>
    <body>
        <header>
            <div class="user_authentication">
                {% if user.is_authenticated %}
                    Signed in as <strong style="color: dodgerblue">{{ user.username }}</strong>
                {% else %}
                    Not signed in.
                {% endif %}
            </div>
                <nav class="navbar navbar-expand-lg py-3">
                    <div class="container">
                    <a href="/" class="navbar-brand">
                        <!-- Logo Image -->
                        <img src="{% static 'auctions/assets/POPIT-logo.png' %}" width="200" alt="" class="d-inline-block align-middle mr-2">
                    </a>

                    <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span class="navbar-toggler-icon"></span></button>

                    <div id="navbarSupportedContent" class="collapse navbar-collapse">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item text-uppercase font-weight-bold"><a href="{% url 'auctions:index' %}" class="nav-link header-links">Active Auctions</a></li>
                            <li class="nav-item text-uppercase font-weight-bold"><a href="{% url 'auctions:categories' %}" class="nav-link header-links">Categories</a></li>
                            {% if user.is_authenticated %}
                                <li class="nav-item text-uppercase font-weight-bold"><a href="{% url 'auctions:my_bids' %}" class="nav-link header-links">My Bids</a></li>
                                <li class="nav-item text-uppercase font-weight-bold"><a href="{% url 'auctions:new' %}" class="nav-link header-links">New Auction</a></li>
                                <li class="nav-item text-uppercase font-weight-bold"><a href="{% url 'auctions:watchlist' %}" class="nav-link header-links">Watchlist</a></li>
                                <li class="nav-item text-uppercase font-weight-bold"><a href="{% url 'auctions:logout' %}" class="nav-link header-links">Log Out</a></li>
                            {% else %}
                                <li class="nav-item text-uppercase font-weight-bold"><a href="{% url 'auctions:login' %}" class="nav-link header-links">Log In</a></li>
                                <li class="nav-item text-uppercase font-weight-bold"><a href="{% url 'auctions:register' %}" class="nav-link header-links">Register</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    </div>
                </nav>
            <hr class="hr-style">
        </header>
        <main>
            {% block body %}
            {% endblock %}
        </main>
    </body>
</html>

cs50w-web-development/project2/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}
    <br>
    <h2>Login</h2>
    <br>
    <div class="form-group align-center">
        <form action="{% url 'auctions:login' %}" method="post">
            {% if message %}
                <div style="color:red">{{ message }}</div>
            {% endif %}
            <br>
            {% csrf_token %}
            <div class="form-group">
                <input autofocus class="form-control" type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <input class="btn btn-dark" type="submit" value="Login">
            <hr class="hr-style">
            <p>Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a></p>
        </form>
    </div>
{% endblock %}

cs50w-web-development/project2/auctions/templates/auctions/mybids.html
{% extends "auctions/layout.html" %}
{% load static %}
{% load my_filters %}
{% block body %}
    <br>
    <h2>My Bids</h2>
    <br>
    {% for bid in bids %}
        <div class="align-center">
            <div class="card text-center mb-5" style="width: 50rem">
                <div class="card-header">{{bid.auction_id.category}}</div>
                <div class="align-center">
                    <img src="{{bid.auction_id.image.url}}" class="card-img-top" alt="{{bid.auction_id.title}} image" style="width: 100%; max-width: 25rem;"/>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ bid.auction_id.title }}</h5>
                    <p class="card-text card-price">{{ bid.price|currency }}</p>
                    {% if bid.auction_id.status %}
                        <span class="badge-text badge badge-success">Active</span>
                        <br><br>
                        <a href="{% url 'auctions:auction' auction_id=bid.auction_id.id %}" class="btn btn-dark">Auction Page</a>
                    {% else %}
                        <span class="badge-text badge badge-danger">Closed</span>
                        <br>
                        {% if user_id == bid.auction_id.winner_user_id %}
                            <span class="badge badge-pill badge-success">You WON</span>
                            <br><br>
                        {% else %}
                            <span class="badge badge-pill badge-danger">You LOST</span>
                            <br><br>
                        {% endif %}
                        <a href="{% url 'auctions:close_auction' auction_id=bid.auction_id.id %}" class="btn btn-dark">Auction Page</a>

                    {% endif %}
                </div>
                <div class="card-footer text-muted">{{bid.bid_date}}</div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

cs50w-web-development/project2/auctions/templates/auctions/new.html
{% extends "auctions/layout.html" %}
{% load static %}
{% block body %}
    <br>
    <h2>Create new auction</h2>
    <br>

    <div class="form-group align-center">
        <form class="form" action="{% url 'auctions:new' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-dark" type="submit">Create</button>
        </form>
    </div>
{% endblock %}

cs50w-web-development/project2/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}
    <br>
    <h2>Register</h2>
    <br>
    <div class="form-group align-center">
        <form action="{% url 'auctions:register' %}" method="post">
            {% if message %}
                <div style="color:red">{{ message }}</div>
            {% endif %}
            <br>
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
            </div>
            <input class="btn btn-dark" type="submit" value="Register">
            <hr class="hr-style">
            <p>Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a></p>
        </form>
    </div>
{% endblock %}