cs50w-web-development/project1/encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.get_entry, name="entry"),
    path("<str:title>/edit/", views.edit, name="edit"),
    path("search/", views.search, name="search"),
    path("new/", views.new, name="new"),
    path("random/", views.random, name="random")
]

cs50w-web-development/project1/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

cs50w-web-development/project1/encyclopedia/models.py
from django.db import models

# Create your models here.

cs50w-web-development/project1/encyclopedia/forms.py
from django import forms


class NewPage(forms.Form):
    title = forms.CharField(label="Title", max_length=255)
    md = forms.CharField(label="Page markdown", widget=forms.Textarea(
        attrs={'placeholder': 'Insert page content in markdown format'}))

cs50w-web-development/project1/encyclopedia/views.py
from django.shortcuts import render
from random import choice
from . import util
import markdown2


def index(request):
    """
    Display a list of all encyclopedia entries
    :param request: The HTTP request
    :type request: HTTP request
    :return: All encyclopedia entries names
    :rtype: list
    """

    entries = util.list_entries()
    return render(request, "encyclopedia/index.html", {
        "entries": entries
    })


def get_entry(request, title):
    """
    Get information about specific entry in the wiki, if there is no
    such entry render an error message
    :param request: The HTTP request
    :type request: HTTP request
    :param title: The entry title
    :type title: str
    :return: Render the entry page with correct data or render error message
    """
    entry = util.get_entry(title)
    if entry:
        # Convert the markdown into HTML
        entry = markdown2.markdown(entry)
        # Render the entry html page with the provided title and the HTML details of the entry
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "entry": entry
        })
    # Entry no found and generating an error
    else:
        return render(request, "encyclopedia/error.html", {
            "message": "404 Page Not Found"
        })


def search(request):
    """
    Search the wiki for specific entry by provided title
    :param request: The HTTP request
    :type request: HTTP request
    :return: Render the entry page with correct data or render error message
    """
    # Getting the list of available entires in order to validate search
    entries = util.list_entries()
    entries = [entry.lower() for entry in entries]
    # Getting the search query inserted by the user
    query = request.GET.get("q").lower()

    # If we have the query provided as entry render the entry page
    if query in entries:
        return get_entry(request, query)
    # Render the closets possible entries
    else:
        substrings = []
        # Traversing entries to check if some entries related to the query
        for entry in entries:
            if query in entry:
               # If the entry is related to the query add it to the list
                substrings.append(entry)
        # Render the search page with the related entires only
        return render(request, "encyclopedia/search.html", {
            "entries": substrings
        })


def new(request):
    """
    Create a new markdown file by gathering the title and the markdown content of the entry from the user
    :param request: The HTTP request
    :type request: HTTP request
    :returns: If GET request render the new page form, if POST create new entry
    """
    if request.method == "GET":
        return render(request, "encyclopedia/new.html")

    # Route accessed by POST request
    else:
        # Extract the information from the form
        form = request.POST
        title = form["title"].lower()
        content = form["md"]

        # Check if this encyclopedia entry already exists
        entries = util.list_entries()

        # forced lowercase for preventing casing issues
        entries = [entry.lower() for entry in entries]

        # Checking if the new page already exists and if it does returns error message
        if title in entries:
            return render(request, "encyclopedia/error.html", {
                "message": "Error, page already exists"
            })
        # Entry not exists so saving the entry md file to the disk and render the new entry
        else:
            util.save_entry(title, content)
            return get_entry(request, title)


def edit(request, title):
    """
    Edit existing page content
    :param request: The HTTP request
    :type request: HTTP request
    :param title: The page title that we are about to edit
    :type title: str
    :returns: If GET request render edit page, if POST update the content of the page
    """

    if request.method == "GET":
        # Get current page markdown content
        content = util.get_entry(title)
        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "content": content
        })

    # Route accessed by POST request so update the new markdown content
    else:
        form = request.POST
        content = form["content"]
        util.save_entry(title, content)
        return get_entry(request, title)


def random(request):
    """ Display random encyclopedia entry """

    entries = util.list_entries()
    rnd = choice(entries)
    return get_entry(request, rnd)

cs50w-web-development/project1/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
    Edit
{% endblock %}

{% block body %}
    <h1>Edit Page</h1>
    <form method="post">
        {% csrf_token %}
        <!-- Form for page's title, autofilled via value -->
        <div class="form-group">
            <label for="title">Title:</label>
            <input type="text" name="title" id="title" class="form-control w-75" value={{title|title}} readonly>
        </div>

        <!-- Form for page's content (textarea), autofilled with the already exists content of the page -->
        <div class="form-group">
            <label for="content">Update Content:</label>
            <textarea class="form-control w-75" name="content" rows="9" id="content">{{ content }}</textarea>
        </div>
        <button class="btn btn-dark">Save</button>
    </form>
{% endblock %}

cs50w-web-development/project1/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %} {{ title|title }} {%endblock %}
{% block body %}
    <a href="/{{title}}/edit/" class="btn btn-dark" role="button">Edit</a>
    {{ entry|safe }}
{% endblock %}

cs50w-web-development/project1/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %} Error {%endblock %}
{% block body%}
    <h1>{{ message }}</h1>
{% endblock %}

cs50w-web-development/project1/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        <!-- Unordered list includes links to all of the entries in the encyclopedia -->
        {% for entry in entries %}
            <li><a href="{{entry}}">{{ entry|title }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

cs50w-web-development/project1/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<!-- Web app icon -->
<link rel="icon" type="image/png" href="{% static 'favicon.ico' %}" />
<html lang="en">
  <head>
    <!-- Page title -->
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap and custom made stylesheets -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet" />
  </head>

  <body>
    <div class="row">
      <!-- Left menu -->
      <div class="sidebar col-lg-2 col-md-3 container-fluid">
        <!-- Wiki Logo -->
        <a href="/"><img src="/static/logo.svg" href="/" /><br /><br /></a>

        <!-- Search bar and the csrf_token -->
        <form action="{% url 'encyclopedia:search' %}" method="get">
          {% csrf_token %}
          <input
            class="search form-control"
            type="text"
            name="q"
            placeholder="Search Pages"
          />
        </form>

        <div>
          <a href="{% url 'encyclopedia:index' %}">&nbspHome</a>
        </div>
        <div>
          <a href="{% url 'encyclopedia:new' %}">&nbspCreate New Page</a>
        </div>
        <div>
          <a href="{% url 'encyclopedia:random' %}">&nbspRandom Page</a>
        </div>
        {% block nav %} {% endblock %}
      </div>
      <div class="main col-lg-10 col-md-9 container-fluid">
        {% block body %}{% endblock %}
      </div>
    </div>
  </body>
</html>

cs50w-web-development/project1/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %} New Page {%endblock%}
{% block body %}
<h1>Create New Page</h1>
<hr/>
<!-- Explains how to work with markdown -->
<p>This page creator supports Markdown only,<a href="https://guides.github.com/features/mastering-markdown/">markdown guide</a></p>

<!-- New page form -->
<form class="form" action="{% url 'encyclopedia:new' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="title">Title</label>
    <input type="text" class="form-control w-75" id="title" name="title" rows="3"></input>
  </div>
  <div class="form-group">
    <label for="md">New page content as markdown</label>
    <textarea class="form-control w-75" rows="9" id="md" name="md" placeholder="Content in markdown"></textarea>
  </div>
  <button class="btn btn-dark" type="submit">Create new entry</button>
</form>
{% endblock %}

cs50w-web-development/project1/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <h1>Search</h1>
    <ul>
        {% if not entries %}
            <h3>No encyclopedia entries that related to this query</h3>
            <a href="/">Click here to see list of entries</a>
        {% else %}
            {% for entry in entries %}
                <li><a href="/{{entry}}">{{ entry }}</a></li>
            {% endfor %}
        {% endif %}
    </ul>
{% endblock %}